definitions:
  user.CreateAccountRequest:
    properties:
      email:
        maxLength: 100
        minLength: 1
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  user.ForgetPasswordRequest:
    properties:
      email:
        maxLength: 100
        minLength: 1
        type: string
    required:
    - email
    type: object
  user.ResetPasswordRequest:
    properties:
      password:
        type: string
      token:
        type: string
    required:
    - password
    - token
    type: object
info:
  contact: {}
paths:
  /api/auth/forget-password:
    post:
      parameters:
      - description: Email
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.ForgetPasswordRequest'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Forget password
  /api/auth/login:
    post:
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: Login
  /api/auth/logout:
    post:
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Logout
  /api/auth/reset-password:
    post:
      parameters:
      - description: Token and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.ResetPasswordRequest'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Reset password
  /api/auth/signup:
    post:
      parameters:
      - description: Email and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.CreateAccountRequest'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: Create account
  /api/auth/verify:
    get:
      parameters:
      - description: Verification token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Verify account
swagger: "2.0"
